apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerbclient
  labels:
    app: kerbclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kerbclient
  template:
    metadata:
      labels:
        app: kerbclient
    spec:
      serviceAccountName: kerb-nfs-sample
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfsclaim
      - name: keytab
        secret:
          secretName: krb-keytab
      # - name: cache-volume
      #   emptyDir: {}
        # hostPath:
          # path: /run/user/1000620000
          # type: DirectoryOrCreate
      securityContext:
        supplementalGroups: [5555]
      containers:
      - image: quay.io/krishchow/krb5_client
        imagePullPolicy: Always
        name: krb5client
        # securityContext:
          # privileged: true
          # runAsUser: 1000620000
        env:
        - name: KRB5CCNAME
          value: "KEYRING:persistent:1000620000"
        - name: USERNAME
          value: "ocpnfs"
        - name: REALM
          value: CORP.OCTO-EMERGING.REDHATAICOE.COM
        volumeMounts:
        - name: nfs-volume
          mountPath: /export
        - name: keytab
          mountPath: "/keytab"
        # - name: cache-volume
        #   mountPath: "/cache"
      restartPolicy: Always
