apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerbclient
  labels:
    app: kerbclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kerbclient
  template:
    metadata:
      labels:
        app: kerbclient
    spec:
      serviceAccountName: kerb-nfs-sample
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfsclaim
      - name: keytab
        secret:
          secretName: krb-keytab
      securityContext:
        supplementalGroups: [5555]
      containers:
      - image: quay.io/krishchow/krb5_client
        imagePullPolicy: Always
        name: krb5client
        env:
        - name: KRB5CCNAME
          value: "KEYRING:persistent:1000620000"
        - name: USERNAME
          value: "ocpnfs"
        - name: REALM
          value: CORP.OCTO-EMERGING.REDHATAICOE.COM
        volumeMounts:
        - name: keytab
          mountPath: "/keytab"
      - image: quay.io/krishchow/krb5_client
        imagePullPolicy: Always
        name: workload
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: nfs-volume
          mountPath: /export
      restartPolicy: Always
