apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol
spec:
  volumeMode: Filesystem
  storageClassName: nfs-class
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
  - sec=krb5
  - rw
  nfs:
    path: /export
    server: nfs.octo-emerging.redhataicoe.com
