apiVersion: v1
kind: ServiceAccount
metadata:
  name: kerb-nfs-sample
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kerb-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kerb-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kerb-role
subjects:
- kind: ServiceAccount
  name: kerb-nfs-sample
  namespace: default